### ISSUE TITLE
TF version

### ISSUE THREAD

**Issue by QUEST2179** [tawssie/ZMPY#1]
Hi,

Thanks for sharing your work. Is it possible to provide tensorflow version demo_shape.ipynb and demo_super.ipynb? numpy version is too slow. Thank you in advance.

**Comment by tawssie** [comment]
The PyTorch version of ZMPY3D is now available [https://github.com/tawssie/ZMPY3D_PT](https://github.com/tawssie/ZMPY3D_PT) . It includes demo notebooks on topics such as shape, superposition, and Zernike moments. I hope this version is helpful for your project.

Additionally, the shape and superposition features for Tensorflow are available through CLIs. You can refer to the source files “ZMPY3D_TF_CLI_ShapeScore.py” and “ZMPY3D_TF_CLI_SuperA2B.py” for more details.
